export default {
  // player
  PLAYER_MOVEMENT_VELOCITY: 40,
  PLAYER_BULLET_MAX_COUNT: 10,
  PLAYER_BULLET_INTERVAL: 300,
  PLAYER_BULLET_SPEED: 300,
  PLAYER_BULLET_LIFESPAN: 3,

  // enemy
  ENEMY_SCOUT_VERTICAL_MOVEMENT_VELOCITY: 9,
  ENEMY_SCOUT_HORIZONTAL_MOVEMENT_VELOCITY: 9,
  ENEMY_FIGHTER_MOVEMENT_VELOCITY: 12,
  ENEMY_SCOUT_MAX_X: 40,
  ENEMY_FIGHTER_BULLET_MAX_COUNT: 10,
  ENEMY_FIGHTER_BULLET_INTERVAL: 2000,
  ENEMY_FIGHTER_BULLET_SPEED: -250,
  ENEMY_FIGHTER_BULLET_LIFESPAN: 3,

  // general
  MAX_HORIZONTAL_VELOCITY: 400,
  MOVEMENT_HORIZONTAL_DRAG: 0.01,
  MAX_VERTICAL_VELOCITY: 160,
  MOVEMENT_VERTICAL_DRAG: 0.01,
}
