export const CUSTOM_EVENTS = {
  ENEMY_INIT: 'ENEMY_INIT',
  ENEMY_DESTROYED: 'ENEMY_DESTROYED',
  PLAYER_SPAWN: 'PLAYER_SPAWN',
  PLAYER_DESTROYED: 'PLAYER_DESTROYED',
  PLAYER_HEALED: 'PLAYER_HEALED',
  GAME_OVER: 'GAME_OVER',
  SHIP_HIT: 'SHIP_HIT',
  SHIP_SHOOT: 'SHIP_SHOOT',
}
